version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=demouser
      - POSTGRES_PASSWORD=demouser
      - POSTGRES_DB=matches
    ports:
      - '5434:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  api:
    container_name: matches-api
    build:
      context: ./matches/
    image: matches:latest
    depends_on:
      - db
    ports:
      - 8081:8080
    environment:
      DB_NAME: "matches"
      DB_USER: "demouser"
      DB_PASSWORD: "demouser"
      DB_HOST: db
      DB_PORT: 5432
    links:
      - db
volumes:
  db:
    driver: local

